// 2026 US Open field — Shinnecock Hills, Southampton NY
// Sorted alphabetically. Update as the official field is confirmed.
export const USOPEN_FIELD = [
  'Abraham Ancer',
  'Adam Scott',
  'Akshay Bhatia',
  'Billy Horschel',
  'Brian Harman',
  'Brooks Koepka',
  'Bryson DeChambeau',
  'Cam Davis',
  'Cameron Smith',
  'Cameron Young',
  'Chris Kirk',
  'Collin Morikawa',
  'Corey Conners',
  'Daniel Berger',
  'Danny Willett',
  'Denny McCarthy',
  'Dustin Johnson',
  'Eric Cole',
  'Harris English',
  'Hideki Matsuyama',
  'J.J. Spaun',
  'Jake Knapp',
  'Jason Day',
  'Joaquin Niemann',
  'Jon Rahm',
  'Jordan Spieth',
  'Justin Rose',
  'Justin Thomas',
  'Keegan Bradley',
  'Kurt Kitayama',
  'Ludvig Aberg',
  'Lucas Glover',
  'Matt Fitzpatrick',
  'Matt McCarty',
  'Max Greyserman',
  'Max Homa',
  'Min Woo Lee',
  'Nick Taylor',
  'Nicolai Hojgaard',
  'Patrick Cantlay',
  'Patrick Reed',
  'Robert MacIntyre',
  'Rory McIlroy',
  'Russell Henley',
  'Sahith Theegala',
  'Scottie Scheffler',
  'Sepp Straka',
  'Shane Lowry',
  'Si Woo Kim',
  'Sungjae Im',
  'Taylor Pendrith',
  'Tom Kim',
  'Tommy Fleetwood',
  'Tony Finau',
  'Tyrrell Hatton',
  'Viktor Hovland',
  'Will Zalatoris',
  'Wyndham Clark',
  'Xander Schauffele',
];
